package supermarket;


import static java.awt.image.ImageObserver.WIDTH;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Thatblackbwoy
 */
public class InvoicePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form InvoicePage
     */
    public InvoicePage() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
//    
//    public void receipt(){
//        String cus = cus_cmb.getItemAt(WIDTH).toString();
//        String subTotal = totalAmount.getText();
//        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//        textArea.setText(textArea.getText() + "\t" + "INVOICE \n");
//        textArea.setText(textArea.getText() + "============================== \n");
//        textArea.setText(textArea.getText() + "\n");
//        textArea.setText(textArea.getText() + "Name "+ "\t" + "cus" + "\n");
//        textArea.setText(textArea.getText() + "\n");
//        Date date = new Date();
//        String thisDate = date.toString();
//        textArea.setText(textArea.getText() + "\n" +thisDate+ "\n");
//        textArea.setText(textArea.getText() + "\n");
//        textArea.setText(textArea.getText() + "item" + "\t" + "qty" + " unit price" + "/t" + "total price" + "\n");
//        textArea.setText(textArea.getText() + "\n");
//        for(int i = 0; i < jTable1.getRowCount(); i++){
//            
//            String item = jTable1.getValueAt(i,0).toString();
//            String qty = jTable1.getValueAt(i,1).toString();
//            String unitPrice = jTable1.getValueAt(i,2).toString();
//            String totalPrice = jTable1.getValueAt(i,3).toString();
//            textArea.setText(textArea.getText() + item + "\t" + qty + "\t" + unitPrice + "\t" + totalPrice + "\t");
//        }
//        textArea.setText(textArea.getText() + "\n");
//        textArea.setText(textArea.getText() + "\t" + subTotal + "/n");
//        textArea.setText(textArea.getText() + "\n");
//        textArea.setText(textArea.getText() + "============================== \n");
//        textArea.setText(textArea.getText() + "\t" + "THANKS COME AGAIN" + "\n");
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setText("Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
